"""empty message

Revision ID: 0c1936a8ed38
Revises: efa75d3bbea5
Create Date: 2023-06-15 20:28:00.788079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1936a8ed38'
down_revision = 'efa75d3bbea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners_pets', schema=None) as batch_op:
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###
