"""empty message

Revision ID: 1137acb3dea2
Revises: b9439eb65f62
Create Date: 2023-06-30 15:23:29.393685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1137acb3dea2'
down_revision = 'b9439eb65f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('addresses_habitant_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_unique_constraint('addresses_habitant_key', ['habitant'])

    # ### end Alembic commands ###
