"""empty message

Revision ID: 1a998bbe84e4
Revises: 8d2944deae6e
Create Date: 2023-06-28 03:33:17.024575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a998bbe84e4'
down_revision = '8d2944deae6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('donor',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('donor',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
