"""empty message

Revision ID: 23d26bc4a423
Revises: 4df0d8d2817c
Create Date: 2023-06-16 15:55:08.918911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d26bc4a423'
down_revision = '4df0d8d2817c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('photos')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_post_id', sa.Integer(), nullable=True))
        batch_op.drop_column('ref_post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('reference_post_id')

    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='photos_pet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photos_pkey'),
    sa.UniqueConstraint('url', name='photos_url_key')
    )
    op.drop_table('pet_photos')
    # ### end Alembic commands ###
