"""empty message

Revision ID: 255ab62941b2
Revises: a950ab58be71
Create Date: 2023-07-05 20:31:58.254154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255ab62941b2'
down_revision = 'a950ab58be71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=False))
        batch_op.drop_column('header')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('header', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('message')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
