"""empty message

Revision ID: 39ed4f9e6df3
Revises: 7fcefe89c195
Create Date: 2023-06-17 01:24:47.483045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39ed4f9e6df3'
down_revision = '7fcefe89c195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners_pets', schema=None) as batch_op:
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
