"""empty message

Revision ID: 4004c0eada4a
Revises: d3110ba63534
Create Date: 2023-06-20 00:03:25.530767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4004c0eada4a'
down_revision = 'd3110ba63534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('habitant',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('habitant',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
