"""empty message

Revision ID: 464bab5bc9e7
Revises: 
Create Date: 2023-06-12 02:45:56.170590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464bab5bc9e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('donor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=30), nullable=False),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.Column('department_number', sa.Integer(), nullable=False),
    sa.Column('commune', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('has_backyard', sa.Boolean(), nullable=True),
    sa.Column('habitant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habitant'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habitant')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('specie', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('need_backyard', sa.Boolean(), nullable=True),
    sa.Column('id_origin', sa.Integer(), nullable=True),
    sa.Column('id_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_origin'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners_pets',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners_pets')
    op.drop_table('pets')
    op.drop_table('addresses')
    op.drop_table('users')
    # ### end Alembic commands ###
