"""empty message

Revision ID: 7fcefe89c195
Revises: 33fb2f6ae53a
Create Date: 2023-06-17 00:37:03.715198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcefe89c195'
down_revision = '33fb2f6ae53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('pet_photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='pet_photos_pet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pet_photos_pkey'),
    sa.UniqueConstraint('url', name='pet_photos_url_key')
    )
    op.drop_table('portfolios')
    # ### end Alembic commands ###
