"""empty message

Revision ID: a950ab58be71
Revises: f050da06101e
Create Date: 2023-07-05 04:56:13.584421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a950ab58be71'
down_revision = 'f050da06101e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('donor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
