"""empty message

Revision ID: d3110ba63534
Revises: 39ed4f9e6df3
Create Date: 2023-06-17 02:39:07.900319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3110ba63534'
down_revision = '39ed4f9e6df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])

    with op.batch_alter_table('owners_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('owners_pets', schema=None) as batch_op:
        batch_op.drop_column('time_stamp')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
