"""empty message

Revision ID: d9421bfefce3
Revises: 23d26bc4a423
Create Date: 2023-06-16 21:17:40.678203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9421bfefce3'
down_revision = '23d26bc4a423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=100), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
