"""empty message

Revision ID: efa75d3bbea5
Revises: 07bd27070774
Create Date: 2023-06-15 01:20:06.384471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa75d3bbea5'
down_revision = '07bd27070774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('department_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint('pets_id_owner_fkey', type_='foreignkey')
        batch_op.drop_constraint('pets_id_origin_fkey', type_='foreignkey')
        batch_op.drop_column('id_origin')
        batch_op.drop_column('id_owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_owner', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_origin', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pets_id_origin_fkey', 'users', ['id_origin'], ['id'])
        batch_op.create_foreign_key('pets_id_owner_fkey', 'users', ['id_owner'], ['id'])

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('department_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
